// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://uhhribwpogrjmxldxgbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoaHJpYndwb2dyam14bGR4Z2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTk5ODcsImV4cCI6MjA2ODkzNTk4N30.hEfD2HWmIXsT-OYryXzEIU51cUu0ImTKjMTJL_u_Ha8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
